import { readdir, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  return (
    await Promise.all(
      entries.map((e) =>
        e.isDirectory() ? walk(`${dir}/${e.name}`) : `${dir}/${e.name}`,
      ),
    )
  ).flat();
}
const assets = (await walk(".next/static"))
  .filter((p) => /\.(js|css|woff2?)$/.test(p))
  .map((p) => p.replace(".next/", "/_next/"));
const template = await readFile("scripts/sw-template.js", "utf8");
const media = (await walk("public/exercises"))
  .filter((p) => p.endsWith(".svg"))
  .map((p) => p.replace("public/", "/"));
const mediaHash = createHash("sha256");
for (const path of media) mediaHash.update(await readFile(`public${path}`));
const shell = [
  "/",
  "/manifest.webmanifest",
  "/icon.svg",
  "/icon-192.png",
  "/icon-512.png",
  ...assets,
];
const id = createHash("sha256")
  .update(shell.join("|") + template + mediaHash.digest("hex"))
  .digest("hex")
  .slice(0, 12);
await writeFile(
  "public/sw.js",
  `// Generated by npm run build.\nconst CACHE='repup-${id}';\nconst ASSETS=${JSON.stringify(shell)};\nconst MEDIA=${JSON.stringify(media)};\n${template}`,
);
console.log(`Offline shell: ${assets.length} versioned assets precached.`);
